import Link from "next/link";
import { AlertTriangleIcon, KeyRoundIcon, ShieldCheckIcon, ShieldIcon } from "lucide-react";
import { redirect } from "next/navigation";

import { ResetPasswordForm } from "@/components/auth/reset-password-form";
import { AuthPageShell } from "@/components/cms/auth-page-shell";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getCurrentAuthenticatedAccount } from "@/server/auth/current-account";

export default async function ResetPasswordPage({
  searchParams,
}: {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}) {
  const authenticated = await getCurrentAuthenticatedAccount();

  if (authenticated) {
    redirect("/account");
  }

  const resolvedSearchParams = searchParams ? await searchParams : {};
  const tokenValue = resolvedSearchParams.token;
  const token = typeof tokenValue === "string" ? tokenValue : "";

  return (
    <AuthPageShell
      eyebrow="Password reset"
      title={token ? "Choose a new password for the Metin2 account" : "A recovery link is required to reset the password"}
      description={
        token
          ? "Finish the recovery flow inside the modern CMS and update the legacy-compatible password used by the current account stack."
          : "Open the exact reset link generated by the recovery request, or create a new one if the previous token expired."
      }
      supportEyebrow="Security notes"
      supportTitle={token ? "Password changes stay compatible with the live server" : "Reset tokens are single-purpose entry points"}
      supportDescription={
        token
          ? "The reset flow updates the account password using the same compatibility rules required by the legacy database and game ecosystem."
          : "This page does not work as a standalone destination. It needs a recovery token created by the recovery workflow first."
      }
      supportItems={[
        {
          title: token ? "Legacy-safe password update" : "Recovery token required",
          description: token
            ? "The new password is written back in the format expected by the existing server-side authentication contract."
            : "Without a valid token in the URL, the CMS cannot know which account recovery request is being completed.",
          icon: token ? <ShieldCheckIcon className="size-4" /> : <AlertTriangleIcon className="size-4" />,
        },
        {
          title: token ? "Recovery-only access" : "Request a fresh link",
          description: token
            ? "Reset links are only meant to finish the recovery process and should not replace normal sign-in or account settings usage."
            : "If the previous link expired or was lost, go back to the recovery page and generate a new reset request.",
          icon: <KeyRoundIcon className="size-4" />,
        },
        {
          title: token ? "Post-reset sign in" : "Sign-in remains separate",
          description: token
            ? "After the password is changed, return to the sign-in page and authenticate normally against the updated account record."
            : "Normal access still starts from the login page. Recovery is only a controlled path back into that flow.",
          icon: <ShieldIcon className="size-4" />,
        },
      ]}
      footer={
        <div className="flex flex-wrap items-center justify-between gap-3">
          <span>Want to go back instead?</span>
          <Link href={token ? "/login" : "/recover"} className="text-zinc-100 underline-offset-4 hover:underline">
            {token ? "Back to sign in" : "Go to recovery"}
          </Link>
        </div>
      }
    >
      {token ? (
        <ResetPasswordForm token={token} />
      ) : (
        <Card className="border-white/10 bg-white/[0.04] shadow-2xl shadow-black/30 backdrop-blur-xl">
          <CardHeader className="space-y-2">
            <CardTitle className="text-2xl text-white">Missing recovery token</CardTitle>
            <CardDescription className="text-zinc-400">
              Open the reset link generated by the recovery flow, or request a new one.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <Alert className="border-amber-400/20 bg-amber-500/10 text-amber-100">
              <AlertTriangleIcon className="size-4" />
              <AlertTitle>Recovery link required</AlertTitle>
              <AlertDescription className="text-amber-100/90">
                This page needs a valid reset token generated by the recovery flow.
              </AlertDescription>
            </Alert>
            <Button asChild className="bg-violet-500 text-white hover:bg-violet-400">
              <Link href="/recover">Go to recovery</Link>
            </Button>
          </CardContent>
        </Card>
      )}
    </AuthPageShell>
  );
}
