import Link from "next/link";
import { AlertTriangleIcon } from "lucide-react";
import { redirect } from "next/navigation";

import { ResetPasswordForm } from "@/components/auth/reset-password-form";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getCurrentAuthenticatedAccount } from "@/server/auth/current-account";

export default async function ResetPasswordPage({
  searchParams,
}: {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}) {
  const authenticated = await getCurrentAuthenticatedAccount();

  if (authenticated) {
    redirect("/account");
  }

  const resolvedSearchParams = searchParams ? await searchParams : {};
  const tokenValue = resolvedSearchParams.token;
  const token = typeof tokenValue === "string" ? tokenValue : "";

  return (
    <main className="min-h-screen bg-[#09090b] px-6 py-16 text-zinc-100">
      <div className="mx-auto flex min-h-[calc(100vh-8rem)] max-w-3xl flex-col justify-center">
        {token ? (
          <ResetPasswordForm token={token} />
        ) : (
          <Card className="border-white/10 bg-white/[0.04] shadow-2xl shadow-black/30 backdrop-blur-xl">
            <CardHeader className="space-y-2">
              <CardTitle className="text-2xl text-white">Missing recovery token</CardTitle>
              <CardDescription className="text-zinc-400">
                Open the reset link generated by the recovery flow, or request a new one.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-5">
              <Alert className="border-amber-400/20 bg-amber-500/10 text-amber-100">
                <AlertTriangleIcon className="size-4" />
                <AlertTitle>Recovery link required</AlertTitle>
                <AlertDescription className="text-amber-100/90">
                  This page needs a valid reset token generated by the recovery flow.
                </AlertDescription>
              </Alert>
              <Button asChild className="bg-violet-500 text-white hover:bg-violet-400">
                <Link href="/recover">Go to recovery</Link>
              </Button>
            </CardContent>
          </Card>
        )}
      </div>
    </main>
  );
}
