import Link from "next/link";
import { redirect } from "next/navigation";

import { ResetPasswordForm } from "@/components/auth/reset-password-form";
import { getCurrentAuthenticatedAccount } from "@/server/auth/current-account";

export default async function ResetPasswordPage({
  searchParams,
}: {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}) {
  const authenticated = await getCurrentAuthenticatedAccount();

  if (authenticated) {
    redirect("/account");
  }

  const resolvedSearchParams = searchParams ? await searchParams : {};
  const tokenValue = resolvedSearchParams.token;
  const token = typeof tokenValue === "string" ? tokenValue : "";

  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col justify-center px-6 py-16">
      {token ? (
        <ResetPasswordForm token={token} />
      ) : (
        <section className="space-y-4 rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm">
          <h1 className="text-2xl font-semibold tracking-tight text-neutral-950">
            Missing recovery token
          </h1>
          <p className="text-sm text-neutral-600">
            Open the reset link generated by the recovery flow, or request a new one.
          </p>
          <Link
            href="/recover"
            className="inline-flex items-center justify-center rounded-xl bg-neutral-950 px-4 py-2 text-sm font-medium text-white transition hover:bg-neutral-800"
          >
            Go to recovery
          </Link>
        </section>
      )}
    </main>
  );
}
